/**
 *   debug.js - loads all debug source files from scripts.json. The scripts.json file gets generated by Grunt
 */

function loadJS(file) {
	var jsElm = document.createElement("script");
	jsElm.type = "application/javascript";
	jsElm.src = file;
	document.body.appendChild(jsElm);
}

function fetch(url, cb) {
	var transport = new XMLHttpRequest();

	transport.onload = function () {
		var response;

		if (this.status === 200) {
			try {
				response = JSON.parse(this.responseText);
			} catch (error) {
				return cb(new Error('Invalid JSON received'));
			}
			cb(null, response);
		} else {
			cb(this.status);
		}
	};

	transport.ontimeout = function() {
		cb(new Error('Timeout'));
	};

	transport.onerror = function () {
		cb(new Error('Network error'));
	};

	transport.open('GET', url);
	transport.timeout = 10000;
	transport.send(null);

}

fetch('js/scripts.json', function(err, scripts) {
	if (err) {
		console.error('Error fetching scripts.json, did you run grunt already?');
		return;
	}

	for (var i=0; i<scripts.length; i++) {
		console.log('DEBUG.js - Loading: ' + scripts[i]);
		loadJS(scripts[i]);
	}
});
